In [13]:
from sklearn.linear_model  import LogisticRegression
from sklearn.svm import SVC 
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
digits = load_digits()

In [ ]:
scaler = MinMaxScaler()
X = scaler.fit_transform(digits.data)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X,digits.target,test_size=0.3)

Logistic Regression

In [22]:
lr = LogisticRegression(max_iter=100)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9703703703703703

SVM

In [27]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9851851851851852

In [28]:
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9703703703703703

---

### K Fold Cross Validation

In [29]:
# Basic Example

from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [32]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index , test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


---

In [33]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [58]:
from sklearn.model_selection import KFold
folds = KFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_random = []

In [59]:
for train_index , test_index in folds.split(X, digits.target):
    X_train , X_test , y_train , y_test = X[train_index] , X[test_index], \
        digits.target[train_index] , digits.target[test_index]
        
    scores_logistic.append(get_score(LogisticRegression(),X_train , X_test , y_train , y_test))
    scores_svm.append(get_score(SVC(),X_train , X_test , y_train , y_test))
    scores_random.append(get_score(RandomForestClassifier(n_estimators=100),X_train , X_test , y_train , y_test))

In [60]:
scores_logistic

[0.9332220367278798, 0.9398998330550918, 0.9198664440734557]

In [63]:
np.mean(scores_logistic)

np.float64(0.9309961046188091)

In [66]:
scores_svm

[0.9649415692821369, 0.9816360601001669, 0.9549248747913188]

In [68]:
np.mean(scores_svm)

np.float64(0.9671675013912076)

In [65]:
scores_random

[0.9382303839732888, 0.9532554257095158, 0.9282136894824707]

In [69]:
np.mean(scores_random)

np.float64(0.9398998330550917)

### cross_val_score function

In [70]:
from sklearn.model_selection import cross_val_score

In [71]:
#logistic regression

cross_val_score(LogisticRegression() , X, digits.target , cv=5)

array([0.94166667, 0.89444444, 0.94707521, 0.96935933, 0.90250696])

In [72]:
#svm

cross_val_score(SVC(), X, digits.target , cv=5 )

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [74]:
# radom forest

cross_val_score(RandomForestClassifier(n_estimators=100), X , digits.target , cv=5)

array([0.92777778, 0.91944444, 0.96100279, 0.9637883 , 0.92479109])

### Parameter Tuning using K-fold 

In [75]:
score1 = cross_val_score(RandomForestClassifier(n_estimators=5), X , digits.target , cv=5)
np.average(score1)

np.float64(0.8636861652739091)

In [77]:
score2 = cross_val_score(RandomForestClassifier(n_estimators=20), X , digits.target , cv=5)
np.average(score2)

np.float64(0.9237836583101208)

In [78]:
score3 = cross_val_score(RandomForestClassifier(n_estimators=50), X , digits.target , cv=5)
np.average(score3)

np.float64(0.9365831012070567)

In [79]:
score4 = cross_val_score(RandomForestClassifier(n_estimators=100), X , digits.target , cv=5)
np.average(score4)

np.float64(0.9332451253481894)