In [14]:
from sklearn.datasets import load_iris 
from sklearn.model_selection import cross_val_score 
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier 
from sklearn.svm import SVC 
import numpy as np 

In [15]:
iris = load_iris()

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(iris.data)

Logistic Regression

In [17]:
lr_scores = cross_val_score(LogisticRegression(),scaled_data , iris.target, cv=5)
lr_scores

array([0.96666667, 1.        , 0.93333333, 0.9       , 1.        ])

In [18]:
np.average(lr_scores)

np.float64(0.9600000000000002)

Support Vector Machine

In [19]:
svm_scores = cross_val_score(SVC(),scaled_data, iris.target , cv=5)
svm_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [20]:
np.average(svm_scores)

np.float64(0.9666666666666666)

Decision Tree

In [22]:
tree_score = cross_val_score(DecisionTreeClassifier(), scaled_data , iris.target , cv=5)
tree_score

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [23]:
np.average(tree_score)

np.float64(0.9600000000000002)

Random Forest

In [25]:
forest_score = cross_val_score (RandomForestClassifier() , scaled_data , iris.target , cv=5)
forest_score

array([0.96666667, 0.96666667, 0.93333333, 0.9       , 1.        ])

In [26]:
np.average(forest_score)

np.float64(0.9533333333333334)